{
 "title": "Cleversafe Accesser",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "accesser", "query": "cleversafe.accesser.*" }
  ]
 },
 "panels": [
  {
   "title": "$accesser - System Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "repeat": "accesser",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(cleversafe.accesser.$accesser.memory.system.*, 5)"
    }
   ]
  },
  {
   "title": "$accesser - System Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "repeat": "accesser",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(cleversafe.accesser.$accesser.load.average*, 0.1), 4)"
    }
   ]
  },
  {
   "title": "$accesser - System Processes Running",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "repeat": "accesser",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(cleversafe.accesser.$accesser.load.processesRunning, 4)"
    }
   ]
  },
  {
   "title": "$accesser - Network Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "repeat": "accesser",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(nonNegativeDerivative(cleversafe.accesser.$accesser.network.bond0.{in,out}), 1), 5)"
    }
   ]
  },
  {
   "title": "$accesser - Accessor Object OPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "repeat": "accesser",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(nonNegativeDerivative(cleversafe.accesser.$accesser.request.*.*.*), 4, 5, 6)"
    }
   ]
  },
  {
   "title": "$accesser - Accessor Object OPS Percentage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "repeat": "accesser",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(asPercent(nonNegativeDerivative(cleversafe.accesser.$accesser.request.*.*.*), #A), 4,5,6)",
     "targetFull": "aliasByNode(asPercent(nonNegativeDerivative(cleversafe.accesser.$accesser.request.*.*.*), sumSeries(nonNegativeDerivative(cleversafe.accesser.$accesser.request.*.*.*))), 4,5,6)"
    }
   ]
  }
 ]
}